# TensorFlow Fundamental - Exercises

Exercises from: https://github.com/mrdbourke/tensorflow-deep-learning#-00-tensorflow-fundamentals-exercises


## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [2]:
import tensorflow as tf
scalar = tf.constant(22)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [3]:
vector = tf.constant([4, 3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

In [4]:
matrix = tf.constant([[4, 5, 6],
                      [8, 1, 56],
                      [11, 4, 7]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 8,  1, 56],
       [11,  4,  7]], dtype=int32)>

## 2. Find the shape, rank and size of the tensors you created in 1.

In [5]:
print("Number of dimensions of scalar: ", scalar.ndim)
print("Number of dimensions of vector: ", vector.ndim)
print("Number of dimensions of matrix: ", matrix.ndim)

Number of dimensions of scalar:  0
Number of dimensions of vector:  1
Number of dimensions of matrix:  2


In [6]:
print("Rank of scalar: ", tf.rank(scalar))
print("Rank of vector: ", tf.rank(vector))
print("Rank of matrix: ", tf.rank(matrix))

Rank of scalar:  tf.Tensor(0, shape=(), dtype=int32)
Rank of vector:  tf.Tensor(1, shape=(), dtype=int32)
Rank of matrix:  tf.Tensor(2, shape=(), dtype=int32)


In [7]:
print("Shape of scalar: ", scalar.shape)
print("Shape of vector: ", vector.shape)
print("Shape of matrix: ", matrix.shape)

Shape of scalar:  ()
Shape of vector:  (2,)
Shape of matrix:  (3, 3)


In [8]:
print("Size of scalar: ", tf.size(scalar))
print("Size of vector: ", tf.size(vector))
print("Size of matrix: ", tf.size(matrix))

Size of scalar:  tf.Tensor(1, shape=(), dtype=int32)
Size of vector:  tf.Tensor(2, shape=(), dtype=int32)
Size of matrix:  tf.Tensor(9, shape=(), dtype=int32)


## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [9]:
import numpy as np
tensor_A = tf.constant(tf.random.uniform(shape=(5, 300), minval=0, maxval=2, dtype=tf.int32))
tensor_B = tf.constant(tf.random.uniform(shape=(5, 300), minval=0, maxval=2, dtype=tf.int32))

In [10]:
tensor_A

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[0, 1, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 0, 1, 0]], dtype=int32)>

In [11]:
tensor_B

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[1, 1, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], dtype=int32)>

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [12]:
tf.matmul(tensor_A, tf.reshape(tensor_B, shape=(300, 5)))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[80, 70, 75, 89, 88],
       [77, 66, 75, 79, 82],
       [74, 78, 82, 75, 72],
       [69, 63, 79, 70, 68],
       [80, 82, 83, 75, 77]], dtype=int32)>

In [13]:
tf.matmul(tensor_A, tf.transpose(tensor_B))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[79, 80, 71, 92, 86],
       [75, 71, 66, 78, 73],
       [78, 70, 75, 87, 92],
       [73, 65, 61, 84, 78],
       [82, 73, 67, 93, 87]], dtype=int32)>

## 5. Multiply the two tensors you created in 3 using dot product.

In [14]:
tf.linalg.tensordot(tf.transpose(tensor_A), tensor_B, axes=1)

<tf.Tensor: shape=(300, 300), dtype=int32, numpy=
array([[0, 2, 2, ..., 1, 1, 2],
       [1, 2, 2, ..., 1, 1, 1],
       [2, 3, 3, ..., 2, 1, 1],
       ...,
       [1, 3, 1, ..., 0, 2, 2],
       [2, 3, 2, ..., 2, 2, 1],
       [1, 2, 2, ..., 1, 0, 1]], dtype=int32)>

In [15]:
tf.linalg.tensordot(tensor_A, tf.transpose(tensor_B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[79, 80, 71, 92, 86],
       [75, 71, 66, 78, 73],
       [78, 70, 75, 87, 92],
       [73, 65, 61, 84, 78],
       [82, 73, 67, 93, 87]], dtype=int32)>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [16]:
tensor_C = tf.constant(tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=2))
tensor_C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.24517703, 1.4170122 , 1.3453095 ],
        [0.6708281 , 1.7886734 , 0.06974077],
        [1.744241  , 1.0092132 , 1.7486453 ],
        ...,
        [0.34116316, 0.55593085, 0.7621877 ],
        [0.6901932 , 1.0537684 , 0.33920407],
        [0.67573786, 1.9802701 , 1.3062072 ]],

       [[1.8234475 , 0.2742355 , 1.7259593 ],
        [1.252769  , 1.7981086 , 0.6226535 ],
        [0.14704156, 1.1758144 , 0.95160246],
        ...,
        [0.42603517, 0.62408733, 1.3060577 ],
        [0.9034898 , 0.82151484, 1.8991323 ],
        [0.90167856, 1.8031466 , 1.1835697 ]],

       [[0.1755588 , 0.77729774, 1.3872905 ],
        [1.4111748 , 1.4612372 , 1.5389512 ],
        [0.42542005, 0.3371966 , 0.910774  ],
        ...,
        [1.3612101 , 0.7714293 , 0.15193987],
        [0.7251699 , 1.3255632 , 1.6205642 ],
        [0.8203471 , 0.51760125, 1.9955165 ]],

       ...,

       [[1.0732663 , 1.6085684 , 0.9994817 ],
        [0.40

## 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [17]:
tf.reduce_min(tensor_C, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[8.62121582e-03, 1.35586262e-02, 1.04308128e-02],
       [3.10873985e-02, 7.92288780e-03, 1.32651329e-02],
       [1.14340782e-02, 1.73091888e-03, 1.91318989e-02],
       [3.54576111e-03, 4.75168228e-03, 6.96158409e-03],
       [5.49387932e-03, 3.21168900e-02, 2.79521942e-03],
       [1.25932693e-03, 4.59194183e-04, 2.03833580e-02],
       [2.39729881e-03, 4.33301926e-03, 2.62260437e-05],
       [1.24049187e-02, 4.07338142e-03, 2.27117538e-03],
       [3.74348164e-02, 2.06637383e-03, 1.17063522e-03],
       [1.20410919e-02, 5.24520874e-05, 1.87237263e-02],
       [5.83052635e-03, 2.80606747e-02, 1.40285492e-03],
       [1.35216713e-02, 5.08785248e-03, 5.41853905e-03],
       [7.85374641e-03, 8.84175301e-03, 9.41753387e-04],
       [1.00200176e-02, 6.95848465e-03, 6.63971901e-03],
       [1.22699738e-02, 4.86898422e-03, 3.49354744e-03],
       [5.04565239e-03, 1.07948780e-02, 2.20489502e-03],
       [1.08714104e-02, 2.59809494e-02

In [18]:
tf.reduce_max(tensor_C, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.9759483, 1.9988422, 1.998205 ],
       [1.9991114, 1.999289 , 1.9990776],
       [1.9983528, 1.9644511, 1.9939268],
       [1.9969046, 1.9983826, 1.9958227],
       [1.9944711, 1.9886358, 1.991338 ],
       [1.9989319, 1.9857163, 1.990438 ],
       [1.9773705, 1.9988253, 1.9827864],
       [1.9911911, 1.9938741, 1.9951572],
       [1.9844182, 1.986381 , 1.9718223],
       [1.998312 , 1.9921441, 1.9990811],
       [1.9996278, 1.9858973, 1.9970114],
       [1.9969323, 1.9965653, 1.9653244],
       [1.9976072, 1.9835868, 1.9951081],
       [1.9863017, 1.9648695, 1.9894092],
       [1.9935939, 1.9970601, 1.9829004],
       [1.9990752, 1.9941285, 1.9985583],
       [1.9637275, 1.9968765, 1.9981549],
       [1.9942324, 1.9932532, 1.9950285],
       [1.9897807, 1.9940162, 1.9923129],
       [1.9786634, 1.9910603, 1.9655519],
       [1.9950356, 1.9959545, 1.9957185],
       [1.9834182, 1.9632852, 1.9974623],
       [1.9965954, 1.97523

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [19]:
tensor_D = tf.constant(tf.random.uniform(shape=(1, 224, 224, 3), minval=0, maxval=100, dtype=tf.int32))
tensor_D

<tf.Tensor: shape=(1, 224, 224, 3), dtype=int32, numpy=
array([[[[90, 52, 14],
         [42, 38, 82],
         [42, 60, 48],
         ...,
         [61, 66, 53],
         [19, 37, 26],
         [ 4, 87, 58]],

        [[45, 14, 32],
         [ 4,  8, 90],
         [11, 48, 13],
         ...,
         [37, 73, 90],
         [44, 92, 73],
         [97, 77, 21]],

        [[87, 17, 25],
         [17, 48, 89],
         [17, 16, 80],
         ...,
         [62, 54, 71],
         [83, 92, 71],
         [48, 54, 72]],

        ...,

        [[89, 70, 78],
         [59, 79, 53],
         [90, 39, 93],
         ...,
         [12, 34,  6],
         [89, 51, 13],
         [63, 85,  6]],

        [[64, 23, 93],
         [ 5, 99, 93],
         [31, 50, 50],
         ...,
         [ 3, 50,  4],
         [65, 41, 52],
         [16, 23,  0]],

        [[51, 16, 84],
         [77, 58, 19],
         [24, 43,  1],
         ...,
         [55, 44, 64],
         [ 6, 44, 30],
         [90, 75, 63]]]], dtype

In [20]:
tensor_D_squeezed = tf.squeeze(tensor_D)
tensor_D_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
array([[[90, 52, 14],
        [42, 38, 82],
        [42, 60, 48],
        ...,
        [61, 66, 53],
        [19, 37, 26],
        [ 4, 87, 58]],

       [[45, 14, 32],
        [ 4,  8, 90],
        [11, 48, 13],
        ...,
        [37, 73, 90],
        [44, 92, 73],
        [97, 77, 21]],

       [[87, 17, 25],
        [17, 48, 89],
        [17, 16, 80],
        ...,
        [62, 54, 71],
        [83, 92, 71],
        [48, 54, 72]],

       ...,

       [[89, 70, 78],
        [59, 79, 53],
        [90, 39, 93],
        ...,
        [12, 34,  6],
        [89, 51, 13],
        [63, 85,  6]],

       [[64, 23, 93],
        [ 5, 99, 93],
        [31, 50, 50],
        ...,
        [ 3, 50,  4],
        [65, 41, 52],
        [16, 23,  0]],

       [[51, 16, 84],
        [77, 58, 19],
        [24, 43,  1],
        ...,
        [55, 44, 64],
        [ 6, 44, 30],
        [90, 75, 63]]], dtype=int32)>

In [21]:
tensor_D_squeezed.shape

TensorShape([224, 224, 3])

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [22]:
tensor_E = tf.constant(tf.random.uniform(minval=0, maxval=20, shape=[10], dtype=tf.int32))
tensor_E

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([13,  6,  6,  9, 19,  4, 12, 10,  0, 16], dtype=int32)>

In [23]:
tf.argmax(tensor_E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

## 10. One-hot encode the tensor you created in 9.

In [24]:
# I go up to 20 because my possible values go up to 20 possibility
tf.one_hot(indices=tensor_E, depth=20)

<tf.Tensor: shape=(10, 20), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     

# TensorFlow Python API selected for Extra-curriculum

## `tf.keras.utils.normalize()`

Normalizes data by scaling it so that it has a mean of zero and a standard deviation of one, which is often used as a pre-processing step in machine learning to improve model convergence and model performance.

In [44]:
tensor_F = tf.constant(tf.random.uniform(shape=(3,3), minval=0, maxval=20, dtype=tf.int32))
tensor_F

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8, 18, 13],
       [ 0, 10,  3],
       [ 1, 16, 14]], dtype=int32)>

In [45]:
tf.keras.utils.normalize(tensor_F)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.34782609, 0.7826087 , 0.56521739],
       [0.        , 1.        , 0.3       ],
       [0.04761905, 0.76190476, 0.66666667]])>

In [50]:
tensor_G = tf.constant(value=[[1, 2, 3],
                              [2, -5, 8],
                              [70, 20, 10]])
tensor_G

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 2, -5,  8],
       [70, 20, 10]], dtype=int32)>

In [51]:
tf.keras.utils.normalize(tensor_G)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 0.33333333,  0.66666667,  1.        ],
       [ 0.22222222, -0.55555556,  0.88888889],
       [ 0.95890411,  0.2739726 ,  0.1369863 ]])>